server:
  port: 8888


## 应用名称
#spring.application.name=blog
## 应用服务 WEB 访问端口
#server.port=8080
## 数据库驱动：
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## 数据源名称
#spring.datasource.name=defaultDataSource
## 数据库连接地址
#spring.datasource.url=jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
## 数据库用户名&密码：
#spring.datasource.username=***
#spring.datasource.password=***


spring:
  datasource:
    url: jdbc:mysql://47.93.60.137:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: luminous1011
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alicloud:
      access-key: LTAI5tAYtyzNzTa22q7sBmsA
      secret-key: LQ1oF5LKnTVbloPyvWD6aJsuwyVv05
      oss:
        endpoint: sts.cn-beijing.aliyuncs.com





file-save-path: C:\Users\luminous\Desktop\0430\images\
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tAYtyzNzTa22q7sBmsA
      keysecret: LQ1oF5LKnTVbloPyvWD6aJsuwyVv05
      bucketname: luminous1011-blog

mybatis:
  #  type-aliases-package: ideal4j.robot.platform.system.*.model,ideal4j.robot.*.*.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    #返回null的属性
    call-setters-on-nulls: true